// Code generated by MockGen. DO NOT EDIT.
// Source: srv.go
//
// Generated by this command:
//
//	mockgen -source=srv.go -destination=./mocks/mock_srv.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Operator0488/go-musthave-metrics-tpl.git/internal/server/model"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// PingDB mocks base method.
func (m *MockService) PingDB(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDB", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDB indicates an expected call of PingDB.
func (mr *MockServiceMockRecorder) PingDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDB", reflect.TypeOf((*MockService)(nil).PingDB), ctx)
}

// SenderGetValue mocks base method.
func (m *MockService) SenderGetValue(ctx context.Context, req models.GetValueRequest) (models.GetValueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SenderGetValue", ctx, req)
	ret0, _ := ret[0].(models.GetValueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SenderGetValue indicates an expected call of SenderGetValue.
func (mr *MockServiceMockRecorder) SenderGetValue(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SenderGetValue", reflect.TypeOf((*MockService)(nil).SenderGetValue), ctx, req)
}

// SenderGetValues mocks base method.
func (m *MockService) SenderGetValues(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SenderGetValues", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SenderGetValues indicates an expected call of SenderGetValues.
func (mr *MockServiceMockRecorder) SenderGetValues(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SenderGetValues", reflect.TypeOf((*MockService)(nil).SenderGetValues), ctx)
}

// SenderPostUpdate mocks base method.
func (m *MockService) SenderPostUpdate(ctx context.Context, req models.PostUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SenderPostUpdate", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SenderPostUpdate indicates an expected call of SenderPostUpdate.
func (mr *MockServiceMockRecorder) SenderPostUpdate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SenderPostUpdate", reflect.TypeOf((*MockService)(nil).SenderPostUpdate), ctx, req)
}

// SenderPostUpdates mocks base method.
func (m *MockService) SenderPostUpdates(ctx context.Context, req []models.PostUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SenderPostUpdates", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SenderPostUpdates indicates an expected call of SenderPostUpdates.
func (mr *MockServiceMockRecorder) SenderPostUpdates(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SenderPostUpdates", reflect.TypeOf((*MockService)(nil).SenderPostUpdates), ctx, req)
}
