// Code generated by MockGen. DO NOT EDIT.
// Source: mux.go
//
// Generated by this command:
//
//	mockgen -source=mux.go -destination=./mocks/mock_srv.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	logger "github.com/Operator0488/go-musthave-metrics-tpl.git/internal/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// GetValue mocks base method.
func (m *MockHandler) GetValue(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetValue", arg0, arg1)
}

// GetValue indicates an expected call of GetValue.
func (mr *MockHandlerMockRecorder) GetValue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockHandler)(nil).GetValue), arg0, arg1)
}

// GetValues mocks base method.
func (m *MockHandler) GetValues(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetValues", arg0, arg1)
}

// GetValues indicates an expected call of GetValues.
func (mr *MockHandlerMockRecorder) GetValues(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValues", reflect.TypeOf((*MockHandler)(nil).GetValues), arg0, arg1)
}

// PostUpdate mocks base method.
func (m *MockHandler) PostUpdate(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostUpdate", arg0, arg1)
}

// PostUpdate indicates an expected call of PostUpdate.
func (mr *MockHandlerMockRecorder) PostUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUpdate", reflect.TypeOf((*MockHandler)(nil).PostUpdate), arg0, arg1)
}

// PostUpdateWithBody mocks base method.
func (m *MockHandler) PostUpdateWithBody(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostUpdateWithBody", arg0, arg1)
}

// PostUpdateWithBody indicates an expected call of PostUpdateWithBody.
func (mr *MockHandlerMockRecorder) PostUpdateWithBody(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUpdateWithBody", reflect.TypeOf((*MockHandler)(nil).PostUpdateWithBody), arg0, arg1)
}

// PostValueWithBody mocks base method.
func (m *MockHandler) PostValueWithBody(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostValueWithBody", arg0, arg1)
}

// PostValueWithBody indicates an expected call of PostValueWithBody.
func (mr *MockHandlerMockRecorder) PostValueWithBody(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostValueWithBody", reflect.TypeOf((*MockHandler)(nil).PostValueWithBody), arg0, arg1)
}

// returnLogger mocks base method.
func (m *MockHandler) returnLogger() logger.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "returnLogger")
	ret0, _ := ret[0].(logger.Logger)
	return ret0
}

// returnLogger indicates an expected call of returnLogger.
func (mr *MockHandlerMockRecorder) returnLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "returnLogger", reflect.TypeOf((*MockHandler)(nil).returnLogger))
}
