// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=./mocks/mock_storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Operator0488/go-musthave-metrics-tpl.git/internal/server/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMemStorage is a mock of MemStorage interface.
type MockMemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMemStorageMockRecorder
	isgomock struct{}
}

// MockMemStorageMockRecorder is the mock recorder for MockMemStorage.
type MockMemStorageMockRecorder struct {
	mock *MockMemStorage
}

// NewMockMemStorage creates a new mock instance.
func NewMockMemStorage(ctrl *gomock.Controller) *MockMemStorage {
	mock := &MockMemStorage{ctrl: ctrl}
	mock.recorder = &MockMemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemStorage) EXPECT() *MockMemStorageMockRecorder {
	return m.recorder
}

// GetValueCounter mocks base method.
func (m *MockMemStorage) GetValueCounter(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueCounter", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValueCounter indicates an expected call of GetValueCounter.
func (mr *MockMemStorageMockRecorder) GetValueCounter(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueCounter", reflect.TypeOf((*MockMemStorage)(nil).GetValueCounter), arg0, arg1)
}

// GetValueGauge mocks base method.
func (m *MockMemStorage) GetValueGauge(arg0 context.Context, arg1 string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueGauge", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValueGauge indicates an expected call of GetValueGauge.
func (mr *MockMemStorageMockRecorder) GetValueGauge(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueGauge", reflect.TypeOf((*MockMemStorage)(nil).GetValueGauge), arg0, arg1)
}

// GetValues mocks base method.
func (m *MockMemStorage) GetValues(arg0 context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValues", arg0)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValues indicates an expected call of GetValues.
func (mr *MockMemStorageMockRecorder) GetValues(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValues", reflect.TypeOf((*MockMemStorage)(nil).GetValues), arg0)
}

// IncrementValue mocks base method.
func (m *MockMemStorage) IncrementValue(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementValue", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementValue indicates an expected call of IncrementValue.
func (mr *MockMemStorageMockRecorder) IncrementValue(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementValue", reflect.TypeOf((*MockMemStorage)(nil).IncrementValue), arg0, arg1, arg2)
}

// PingDB mocks base method.
func (m *MockMemStorage) PingDB(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDB", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDB indicates an expected call of PingDB.
func (mr *MockMemStorageMockRecorder) PingDB(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDB", reflect.TypeOf((*MockMemStorage)(nil).PingDB), arg0)
}

// SaveValue mocks base method.
func (m *MockMemStorage) SaveValue(arg0 context.Context, arg1 string, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveValue", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveValue indicates an expected call of SaveValue.
func (mr *MockMemStorageMockRecorder) SaveValue(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveValue", reflect.TypeOf((*MockMemStorage)(nil).SaveValue), arg0, arg1, arg2)
}

// SaveValues mocks base method.
func (m *MockMemStorage) SaveValues(arg0 context.Context, arg1 []models.PostUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveValues", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveValues indicates an expected call of SaveValues.
func (mr *MockMemStorageMockRecorder) SaveValues(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveValues", reflect.TypeOf((*MockMemStorage)(nil).SaveValues), arg0, arg1)
}
