// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=./mocks/mock_storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Operator0488/go-musthave-metrics-tpl.git/internal/server/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMemStorage is a mock of MemStorage interface.
type MockMemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMemStorageMockRecorder
	isgomock struct{}
}

// MockMemStorageMockRecorder is the mock recorder for MockMemStorage.
type MockMemStorageMockRecorder struct {
	mock *MockMemStorage
}

// NewMockMemStorage creates a new mock instance.
func NewMockMemStorage(ctrl *gomock.Controller) *MockMemStorage {
	mock := &MockMemStorage{ctrl: ctrl}
	mock.recorder = &MockMemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemStorage) EXPECT() *MockMemStorageMockRecorder {
	return m.recorder
}

// AddData mocks base method.
func (m *MockMemStorage) AddData(arg0 models.MetricStore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddData indicates an expected call of AddData.
func (mr *MockMemStorageMockRecorder) AddData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddData", reflect.TypeOf((*MockMemStorage)(nil).AddData), arg0)
}

// GetData mocks base method.
func (m *MockMemStorage) GetData() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData")
	ret0, _ := ret[0].(error)
	return ret0
}

// GetData indicates an expected call of GetData.
func (mr *MockMemStorageMockRecorder) GetData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockMemStorage)(nil).GetData))
}

// GetValueCounter mocks base method.
func (m *MockMemStorage) GetValueCounter(arg0 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueCounter", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValueCounter indicates an expected call of GetValueCounter.
func (mr *MockMemStorageMockRecorder) GetValueCounter(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueCounter", reflect.TypeOf((*MockMemStorage)(nil).GetValueCounter), arg0)
}

// GetValueGauge mocks base method.
func (m *MockMemStorage) GetValueGauge(arg0 string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueGauge", arg0)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValueGauge indicates an expected call of GetValueGauge.
func (mr *MockMemStorageMockRecorder) GetValueGauge(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueGauge", reflect.TypeOf((*MockMemStorage)(nil).GetValueGauge), arg0)
}

// GetValues mocks base method.
func (m *MockMemStorage) GetValues() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValues")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValues indicates an expected call of GetValues.
func (mr *MockMemStorageMockRecorder) GetValues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValues", reflect.TypeOf((*MockMemStorage)(nil).GetValues))
}

// IncrementValue mocks base method.
func (m *MockMemStorage) IncrementValue(arg0 string, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementValue indicates an expected call of IncrementValue.
func (mr *MockMemStorageMockRecorder) IncrementValue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementValue", reflect.TypeOf((*MockMemStorage)(nil).IncrementValue), arg0, arg1)
}

// SaverValue mocks base method.
func (m *MockMemStorage) SaverValue(arg0 string, arg1 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaverValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaverValue indicates an expected call of SaverValue.
func (mr *MockMemStorageMockRecorder) SaverValue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaverValue", reflect.TypeOf((*MockMemStorage)(nil).SaverValue), arg0, arg1)
}
